//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGTPPE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int idTicket { get; set; }
        public string emplacementMaterielTicket { get; set; }
        public string typeMaterielTicket { get; set; }
        public string descriptionIncident { get; set; }
        public System.DateTime dateCreationIncident { get; set; }
        public System.DateTime dateClotureIncident { get; set; }
        public int idUtilisateur { get; set; }
        public string numeroSerieMateriel { get; set; }
        public string nomCellule { get; set; }
        public string etatStatut { get; set; }
    
        public virtual CELLULE CELLULE { get; set; }
        public virtual MATERIEL MATERIEL { get; set; }
        public virtual STATUT STATUT { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
